<div style="display: flex; align-items: center; justify-content: center; gap: 20px;">
    <img src="https://logo-marque.com/wp-content/uploads/2021/03/Kayak-Logo.png" alt="Image Gauche" style="width: 400px; height: auto;">
    <div style="font-size: 26px; text-align: center;">
        <h1>
            <span style="font-weight: bold; color: #FF6A06; text-decoration: underline;">
                Kayak Project
            </span>
        </h1>
    </div>
    <img src="https://logo-marque.com/wp-content/uploads/2021/03/Kayak-Logo.png" alt="Image Droite" style="width: 400px; height: auto;">
</div>

<h1 style="font-size: 18px; text-align: center; font-style: italic;">
    <span style="font-weight: bold; color: #FF6A06">
        Student : Loic VALENTINI
    </span>
</h1>

# 0. Imports

In [23]:
# Initial imports

import requests
import pandas as pd
import json
import time
import os
from dotenv import load_dotenv
import pickle

# 1. Retrieving GPS coordinates of cities via Nominatim API

In [2]:
# Creation of the city list recommended by the marketing team

list_of_cities = ["Mont Saint Michel",
"St Malo",
"Bayeux",
"Le Havre",
"Rouen",
"Paris",
"Amiens",
"Lille",
"Strasbourg",
"Chateau du Haut Koenigsbourg",
"Colmar",
"Eguisheim",
"Besancon",
"Dijon",
"Annecy",
"Grenoble",
"Lyon",
"Gorges du Verdon",
"Bormes les Mimosas",
"Cassis",
"Marseille",
"Aix en Provence",
"Avignon",
"Uzes",
"Nimes",
"Aigues Mortes",
"Saintes Maries de la mer",
"Collioure",
"Carcassonne",
"Ariege",
"Toulouse",
"Montauban",
"Biarritz",
"Bayonne",
"La Rochelle"]

In [7]:
# Using the Nominatim API to retrieve GPS coordinates for each city

url = "https://nominatim.openstreetmap.org/search" # API URL

results = []  # Empty list to collect results

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Edge/91.0.864.59"  # User-Agent
    }

for city in list_of_cities : # Integrating each city from the list into the API

    params = {
        "city": city,   # City name
        "format": "json",  # JSON Format
    }

    time.sleep(2) # Pause in the loop to avoid blocking - 2s between each iteration

    response = requests.get(url, params=params, headers=headers) # Definition of the request response

    if response.status_code == 200:     # If No error
        data = response.json()
        if data:                        # If the data are well collected
            results.append({            # Result append
                "Ville": city,
                "Latitude": data[0]['lat'],
                "Longitude": data[0]['lon']
            })
        else:                           # In case of error
            results.append({
                "Ville": city,          # None values for the concerned city
                "Latitude": None,
                "Longitude": None
            })
    else:                               # If Error
        print(f"Erreur {response.status_code}: Impossible to get data for {city}.") # Print of a message error that incudes the concerned city
        results.append({
            "Ville": city,              # None values for this city
            "Latitude": None,
            "Longitude": None
        })

df_35_cities_GPS = pd.DataFrame(results)   # Df_35_cities_GPS creation with the retrieved data
print(df_35_cities_GPS)                    # Print of this df

if not os.path.exists('kayak_results'):    # Folder creation if missing 
    os.makedirs('kayak_results')

df.to_csv("kayak_results/35_cities_GPS.csv", index=True) # csv recording into the folder

print("CSV file recorded with index !")     # Display of a success message !

                           Ville            Latitude           Longitude
0              Mont Saint Michel          48.6359541  -1.511459954959514
1                        St Malo           48.649518          -2.0260409
2                         Bayeux          49.2764624          -0.7024738
3                       Le Havre          49.4938975           0.1079732
4                          Rouen          49.4404591           1.0939658
5                          Paris          48.8588897  2.3200410217200766
6                         Amiens          49.8941708           2.2956951
7                          Lille          50.6365654           3.0635282
8                     Strasbourg           48.584614           7.7507127
9   Chateau du Haut Koenigsbourg          48.2495226           7.3454923
10                        Colmar          48.0777517           7.3579641
11                     Eguisheim          48.0447968           7.3079618
12                      Besancon          47.2380222           6.0243622
13                         Dijon          47.3215806           5.0414701
14                        Annecy          45.8992348           6.1288847
15                      Grenoble          45.1875602           5.7357819
16                          Lyon          45.7578137           4.8320114
17              Gorges du Verdon          43.7496562           6.3285616
18            Bormes les Mimosas          43.1506968           6.3419285
19                        Cassis          43.2140359           5.5396318
20                     Marseille          43.2961743           5.3699525
21               Aix en Provence          43.5298424           5.4474738
22                       Avignon          43.9492493           4.8059012
23                          Uzes          44.0121279           4.4196718
24                         Nimes          43.8374249           4.3600687
25                 Aigues Mortes          43.5661521             4.19154
26      Saintes Maries de la mer          43.4515922           4.4277202
27                     Collioure            42.52505           3.0831554
28                   Carcassonne          43.2130358           2.3491069
29                        Ariege         51.18111155  -55.98447423947262
30                      Toulouse          43.6044622           1.4442469
31                     Montauban          44.0175835           1.3549991
32                      Biarritz  43.471143749999996  -1.552726590666314
33                       Bayonne          43.4945144          -1.4736657
34                   La Rochelle           46.159732          -1.1515951
CSV file recorded with index !

<h1 style="font-size: 18px;">
    This list of GPS coordinates will allow us to put them in a weather API to retrieve weather forecast. It can be found in kayak_results/35_cities_GPS.csv
</h1>

# 2. Retrieving 7-day weather forecast via the Meteomatics API

In [8]:
# Necessary libraires to import

import datetime as dt
import meteomatics.api as api

In [120]:
# List creation from the dataframe df_35_cities_GPS, coming from the csv 35_cities_GPS

import pandas as pd

# Replace 'file_path.csv' with your actual CSV file path
df_35_cities_GPS = pd.read_csv('kayak_results/35_cities_GPS.csv')

latitudes_list = df_35_cities_GPS['Latitude'].tolist()
longitudes_list = df_35_cities_GPS['Longitude'].tolist()
cities_list = df_35_cities_GPS['Ville'].tolist()

In [10]:
# Use of environment variables (username and password)

load_dotenv()

True

In [12]:
# Using the Meteomatics API to retrieve 7-days weather forecasts

username = os.environ["METEOMATICS_KEY"]
password = os.environ["METEOMATICS_SECRET_KEY"]

                                                                            # List of retried parameters (10 max. with the free API key)
parameters = ['t_2m:C', 't_max_2m_24h:C', 't_min_2m_24h:C',                 # Temperature °C (at each time point, and min/max for the previous 24 hours)
              'msl_pressure:hPa',                                           # Pressure hPa (at each time point)
              'precip_1h:mm', 'precip_24h:mm',                              # Rain mm (previous hour and previous 24hours)
              'weather_symbol_1h:idx', 'weather_symbol_24h:idx' ,           # Weather symbol index ("giving an overall impression of the weather state", previous hour and previous 24hours)
              'uv:idx',                                                     # UV index (at each time point)
              'wind_speed_10m:ms']                                          # Windforce in m/s (at each time point)


model = 'mix'                                                               # Combine of different models (intellignet blend), recommended by meteomatics

startdate = dt.datetime.utcnow().replace(minute=0, second=0, microsecond=0) # Start date = When the API is called
enddate = startdate + dt.timedelta(days=7)                                  # End date = 7 days after the Start date
interval = dt.timedelta(hours=1)                                            # 1 point per hour (expect 7*24 = 168 points per parameter and per city)


dataframes = {}                     # Creation of result dictionnary to retrieved all the collected data

if not os.path.exists('kayak_results/weather_data'):    # Folder creation if missing
    os.makedirs('kayak_results/weather_data')


for city, lat, lon in zip(cities_list, latitudes_list, longitudes_list):    # Loop for each city
    city_weather_data = api.query_time_series([(lat, lon)], startdate, enddate, interval, parameters, username, password, model)     # Launch the meteomatics API

    time.sleep(2)                   # Pause in the loop to avoid blocking - 2s between each iteration

    if city_weather_data is not None and not city_weather_data.empty: # Save the data only if the result is correct

        df_weather_city = pd.DataFrame(city_weather_data).reset_index(drop=False).reset_index(drop=True)   # Create the dataframe for each city, reset the index to columns, then add a new index starting from 0.
        dataframes[city] = df_weather_city                                                           # Place each dataframe in the dictionnary
        globals()[f"df_{city}"] = df_weather_city                                                    # Création of a dynamic variable including city name 
        df_weather_city['city'] = city                                                               # Adding of a column "city" in each df 
        df_weather_city.to_csv(os.path.join('kayak_results/weather_data', f"{city}_weather_data.csv"), index=False)   # CSV storage of each dataframe

<h1 style="font-size: 18px;">
    All the necessary data for the 35 cities has been collected. It will be cleaned and stored in usable tables to facilitate the selection of the final 5 cities. It can be found in kayak_results/weather_data/
</h1>

# 3. Cleaning and visualizing the API-collected data to determine which cities to keep

<h1 style="font-size: 18px;">

Selection Criteria for the 5 "Best-Weather" Cities:

- Limited rain in the next 7 days (if max_rain exceeds 1mm at any point during the week, the city is eliminated). Rain is measured between 7 AM and 11 PM, so nighttime rain is not considered.
- Cities are ranked by average temperature (higher is better, as it's more comfortable in winter).
- Cities are ranked by average UV index (sun exposure, higher is better). UV is measured between 8 AM and 8 PM (sunrise-sunset)
- The two rankings are multiplied, and the 5 cities with the highest scores are selected.
</h1>

In [1]:
# Recreating a weather dataframe for each city from the stored CSV files to avoid redundant API calls

import glob
import pandas as pd

filepath = 'kayak_results/weather_data/'

list_of_cities = ["Mont Saint Michel",
"St Malo",
"Bayeux",
"Le Havre",
"Rouen",
"Paris",
"Amiens",
"Lille",
"Strasbourg",
"Chateau du Haut Koenigsbourg",
"Colmar",
"Eguisheim",
"Besancon",
"Dijon",
"Annecy",
"Grenoble",
"Lyon",
"Gorges du Verdon",
"Bormes les Mimosas",
"Cassis",
"Marseille",
"Aix en Provence",
"Avignon",
"Uzes",
"Nimes",
"Aigues Mortes",
"Saintes Maries de la mer",
"Collioure",
"Carcassonne",
"Ariege",
"Toulouse",
"Montauban",
"Biarritz",
"Bayonne",
"La Rochelle"]

# Loop to re-create a df per city, named df_city

for city in list_of_cities:
    
    filename = f"{city}_weather_data.csv"

    # Complete filepath
    complete_filepath = filepath + filename
    
    # Corresponding dataframe
    globals()[f"df_{city}"] = pd.read_csv(complete_filepath)

In [2]:
# Transform all validate columns into datetime format

for city in list_of_cities:
    df_city = globals().get(f"df_{city}")
    df_city["validdate"] = pd.to_datetime(df_city["validdate"])

In [3]:
# Dataframe creation about rain measurements. 3 columns : city_name, avg_rain and max_rain between 7AM/11PM


rain_df = pd.DataFrame(columns=['city_name', 'avg_rain', 'max_rain'])


for city in list_of_cities:
    df_city_loop = globals().get(f"df_{city}")  # Collect each city dataframe

    if df_city_loop is not None and not df_city_loop.empty:

        # Time filter
        df_city_loop_filtered = df_city_loop[(df_city_loop['validdate'].dt.hour >= 7) & (df_city_loop['validdate'].dt.hour < 23)]

        # Rain average
        avg_rain = df_city_loop_filtered["precip_1h:mm"].mean()

        # Rain max
        max_rain = df_city_loop_filtered["precip_1h:mm"].max()

        # Create a temporary DataFrame to append
        temporary_df = pd.DataFrame({'city_name': [city], 'avg_rain': [avg_rain], 'max_rain': [max_rain]})

        # Concatenate the temporary DataFrame with the main DataFrame
        rain_df = pd.concat([rain_df, temporary_df], ignore_index=True)


# Print the results
rain_df

C:\Users\valen\AppData\Local\Temp\ipykernel_12260\976803323.py:25: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  rain_df = pd.concat([rain_df, temporary_df], ignore_index=True)

                       city_name  avg_rain  max_rain
0              Mont Saint Michel  0.033186      0.49
1                        St Malo  0.051770      0.61
2                         Bayeux  0.015487      0.40
3                       Le Havre  0.015664      0.25
4                          Rouen  0.026283      0.39
5                          Paris  0.043186      0.55
6                         Amiens  0.019204      0.34
7                          Lille  0.014602      0.20
8                     Strasbourg  0.096106      0.70
9   Chateau du Haut Koenigsbourg  0.112212      0.81
10                        Colmar  0.109381      0.66
11                     Eguisheim  0.108938      0.63
12                      Besancon  0.076814      0.83
13                         Dijon  0.065044      0.59
14                        Annecy  0.052832      0.68
15                      Grenoble  0.035398      0.38
16                          Lyon  0.076991      1.17
17              Gorges du Verdon  0.071770      0.86
18            Bormes les Mimosas  0.053982      0.57
19                        Cassis  0.044602      0.53
20                     Marseille  0.038673      0.45
21               Aix en Provence  0.011593      0.19
22                       Avignon  0.157080      1.66
23                          Uzes  0.236460      2.00
24                         Nimes  0.240885      1.71
25                 Aigues Mortes  0.290973      1.97
26      Saintes Maries de la mer  0.354513      2.33
27                     Collioure  0.195929      3.78
28                   Carcassonne  0.036372      0.54
29                        Ariege  0.151327      3.10
30                      Toulouse  0.028496      0.28
31                     Montauban  0.003186      0.36
32                      Biarritz  0.058319      1.13
33                       Bayonne  0.062566      1.10
34                   La Rochelle  0.042478      0.51

In [4]:
# Dataframe creation about temperature measurements

temperature_df = pd.DataFrame(columns=['city_name', 'avg_temp', 'max_temp'])


for city in list_of_cities:
    df_city_loop = globals().get(f"df_{city}")  # Collect each city dataframe

    if df_city_loop is not None and not df_city_loop.empty:

        # temp average
        avg_temp = df_city_loop["t_2m:C"].mean()

        # temp max
        max_temp = df_city_loop["t_2m:C"].max()

        # Create a temporary DataFrame to append
        temporary_df = pd.DataFrame({'city_name': [city], 'avg_temp': [avg_temp], 'max_temp': [max_temp]})

        # Concatenate the temporary DataFrame with the main DataFrame
        temperature_df = pd.concat([temperature_df, temporary_df], ignore_index=True)


# Print the results
temperature_df

C:\Users\valen\AppData\Local\Temp\ipykernel_12260\3515248455.py:21: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  temperature_df = pd.concat([temperature_df, temporary_df], ignore_index=True)

                       city_name   avg_temp  max_temp
0              Mont Saint Michel   3.820710       8.5
1                        St Malo   4.568639       8.7
2                         Bayeux   3.562722       9.0
3                       Le Havre   3.926627       7.8
4                          Rouen   3.252663       9.0
5                          Paris   3.027811       7.3
6                         Amiens   3.007692       8.7
7                          Lille   3.079290       8.7
8                     Strasbourg   1.118935       6.1
9   Chateau du Haut Koenigsbourg  -0.890533       6.5
10                        Colmar   1.303550       8.2
11                     Eguisheim   1.436095       8.7
12                      Besancon   1.753254       8.6
13                         Dijon   2.414201       9.4
14                        Annecy   0.648521       8.8
15                      Grenoble   3.724852      13.3
16                          Lyon   2.845562      10.7
17              Gorges du Verdon   3.437870      11.7
18            Bormes les Mimosas   8.899408      14.5
19                        Cassis   9.598817      15.3
20                     Marseille   9.067456      15.4
21               Aix en Provence   6.524852      15.6
22                       Avignon   6.155621      11.9
23                          Uzes   5.711834      11.2
24                         Nimes   6.503550      12.4
25                 Aigues Mortes   7.153846      13.5
26      Saintes Maries de la mer   7.860947      13.8
27                     Collioure   9.145562      15.0
28                   Carcassonne   6.208876      12.7
29                        Ariege -10.278107       1.2
30                      Toulouse   5.122485      12.3
31                     Montauban   4.399408      12.9
32                      Biarritz   6.487574      13.1
33                       Bayonne   6.773964      14.0
34                   La Rochelle   4.301775      10.6

In [5]:
# Dataframe creation about uv_index measurements

uv_index_df = pd.DataFrame(columns=['city_name', 'avg_uv_index', 'max_uv_index'])


for city in list_of_cities:
    df_city_loop = globals().get(f"df_{city}")  # Collect each city dataframe

    if df_city_loop is not None and not df_city_loop.empty:

        # Time filter
        df_city_loop_filtered = df_city_loop[(df_city_loop['validdate'].dt.hour >= 8) & (df_city_loop['validdate'].dt.hour < 20)]

        # uv_index average
        avg_uv_index = df_city_loop["uv:idx"].mean()

        # uv_index max
        max_uv_index = df_city_loop["uv:idx"].max()

        # Create a temporary DataFrame to append
        temporary_df = pd.DataFrame({'city_name': [city], 'avg_uv_index': [avg_uv_index], 'max_uv_index': [max_uv_index]})

        # Concatenate the temporary DataFrame with the main DataFrame
        uv_index_df = pd.concat([uv_index_df, temporary_df], ignore_index=True)


# Print the results
uv_index_df

C:\Users\valen\AppData\Local\Temp\ipykernel_12260\3385378747.py:24: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  uv_index_df = pd.concat([uv_index_df, temporary_df], ignore_index=True)

                       city_name  avg_uv_index  max_uv_index
0              Mont Saint Michel      0.213018           3.0
1                        St Malo      0.213018           3.0
2                         Bayeux      0.213018           3.0
3                       Le Havre      0.242604           3.0
4                          Rouen      0.218935           3.0
5                          Paris      0.224852           3.0
6                         Amiens      0.224852           3.0
7                          Lille      0.213018           3.0
8                     Strasbourg      0.242604           3.0
9   Chateau du Haut Koenigsbourg      0.254438           3.0
10                        Colmar      0.236686           3.0
11                     Eguisheim      0.242604           3.0
12                      Besancon      0.248521           3.0
13                         Dijon      0.195266           2.0
14                        Annecy      0.355030           4.0
15                      Grenoble      0.378698           3.0
16                          Lyon      0.224852           3.0
17              Gorges du Verdon      0.455621           4.0
18            Bormes les Mimosas      0.331361           3.0
19                        Cassis      0.272189           3.0
20                     Marseille      0.289941           4.0
21               Aix en Provence      0.343195           4.0
22                       Avignon      0.355030           4.0
23                          Uzes      0.349112           4.0
24                         Nimes      0.337278           4.0
25                 Aigues Mortes      0.337278           4.0
26      Saintes Maries de la mer      0.343195           3.0
27                     Collioure      0.349112           3.0
28                   Carcassonne      0.331361           3.0
29                        Ariege      0.159763           2.0
30                      Toulouse      0.390533           3.0
31                     Montauban      0.396450           3.0
32                      Biarritz      0.402367           3.0
33                       Bayonne      0.396450           3.0
34                   La Rochelle      0.289941           3.0

In [6]:
# collect of the GPS coordinates into  datframe from the stored CSV

df_gps = pd.read_csv('kayak_results/35_cities_GPS.csv')     # Collect the dataframe
df_gps = df_gps[['Ville','Latitude','Longitude']]           # Keep the useful columns
df_gps = df_gps.rename(columns={'Ville': 'city_name'})      # Rename the key

df_gps

                       city_name   Latitude  Longitude
0              Mont Saint Michel  48.635954  -1.511460
1                        St Malo  48.649518  -2.026041
2                         Bayeux  49.276462  -0.702474
3                       Le Havre  49.493898   0.107973
4                          Rouen  49.440459   1.093966
5                          Paris  48.853495   2.348391
6                         Amiens  49.894171   2.295695
7                          Lille  50.636565   3.063528
8                     Strasbourg  48.584614   7.750713
9   Chateau du Haut Koenigsbourg  48.249523   7.345492
10                        Colmar  48.077752   7.357964
11                     Eguisheim  48.044797   7.307962
12                      Besancon  47.238022   6.024362
13                         Dijon  47.321581   5.041470
14                        Annecy  45.899235   6.128885
15                      Grenoble  45.187560   5.735782
16                          Lyon  45.757814   4.832011
17              Gorges du Verdon  43.749656   6.328562
18            Bormes les Mimosas  43.150697   6.341928
19                        Cassis  43.214036   5.539632
20                     Marseille  43.296174   5.369953
21               Aix en Provence  43.529842   5.447474
22                       Avignon  43.949249   4.805901
23                          Uzes  44.012128   4.419672
24                         Nimes  43.837425   4.360069
25                 Aigues Mortes  43.566152   4.191540
26      Saintes Maries de la mer  43.451592   4.427720
27                     Collioure  42.525050   3.083155
28                   Carcassonne  43.213036   2.349107
29                        Ariege  51.181112 -55.984474
30                      Toulouse  43.604462   1.444247
31                     Montauban  44.017584   1.354999
32                      Biarritz  43.471144  -1.552727
33                       Bayonne  43.494514  -1.473666
34                   La Rochelle  46.159732  -1.151595

In [7]:
# Merge of the 3 weather Dataframes + GPS

import os

merged1_df = pd.merge(rain_df, temperature_df, on='city_name', how='inner')  # Merge rain_df and temperature_df
merged2_df = pd.merge(merged1_df, uv_index_df, on='city_name', how='inner')  # Merge with uv_index_df
weather_decision_merged_df = pd.merge(merged2_df, df_gps, on='city_name', how='inner')  # Merge with df_gps

weather_decision_merged_df.to_csv(os.path.join('kayak_results', f"weather_decision.csv"), index=False)   # CSV storage of this dataframe

print("CSV file recorded !")     # Display of a success message !

CSV file recorded !

In [8]:
# Barchart of max_rain per city

import plotly.express as px

# Add a column to define the color (Red if > 1mm, Green otherwise)
weather_decision_merged_df['color'] = weather_decision_merged_df['max_rain'].apply(lambda x: 'red (>1mm)' if x > 1 else 'green (<1mm)')

# Sort the data by max_rain (from highest to lowest)
weather_decision_merged_df = weather_decision_merged_df.sort_values(by='max_rain', ascending=False)

# Create the chart with Plotly Express
fig = px.bar(weather_decision_merged_df, x='city_name', y='max_rain', 
             title="Max Rainfall per City",
             labels={'max_rain': 'Max Rain (mm)', 'city_name': 'City'},
             text='max_rain',  
             color='color',  # Color gradient based on rainfall
             color_discrete_map={'red (>1mm)': 'red', 'green (<1mm)': 'green'}  # Define the colors
            )

# Customize the title and layout
fig.update_layout(
    title={
        'text': "Max Rainfall per City",
        'x': 0.5,  # Center the title
        'xanchor': 'center',
        'yanchor': 'top',
        'font': dict(family="Arial", size=20, color="black")  # Increase size + black color
    }, # Bold and styled title
    
    xaxis_title=None  # Remove the title of the X-axis
)

# Show the figure
fig.show()

In [14]:
# Same vizualisation on a France map

# Activate Mapbox (requires a Mapbox API key, but works with the public version)
px.set_mapbox_access_token("pk.eyJ1IjoibWFwYm94IiwiYSI6ImNqZ2czZzYzaTAwN3kyeHFwbXExdGVvbjYifQ.CqHfA9sT2IRKIIeOkeV6GA")

# Add a column to define the color (Red if > 1mm, Green otherwise)
weather_decision_merged_df['color'] = weather_decision_merged_df['max_rain'].apply(lambda x: 'red (>1mm)' if x > 1 else 'green (<1mm)')

# Create the map with Plotly Express
fig = px.scatter_mapbox(
    weather_decision_merged_df,
    lat='Latitude',
    lon='Longitude',
    color='color',  # Custom colors
    size='max_rain',  # Size of the points proportional to max_rain
    size_max=20,  # Max size of the points
    hover_name='city_name',
    hover_data={'Latitude': False, 'Longitude': False, 'max_rain': True},  # Hover info
    color_discrete_map={'red (>1mm)': 'red', 'green (<1mm)': 'green'},  # Custom legend
    title="Rainfall Map of France"
)

# Customize the display
fig.update_layout(
    height=800,
    width = 1000,
    mapbox_zoom=5,
    mapbox_style="carto-positron",  # Map style
    mapbox_center={"lat": 46.6031, "lon": 1.8883},  # Center on France
    title={
        'text': "Rainfall Map of France",
        'x': 0.5,
        'xanchor': 'center',
        'font': dict(size=20, color="black")
    }
)

# Display the map
fig.show()

In [22]:
# Store this map in html

import plotly.express as px
import plotly.io as pio

# Save this map in HTML format instead of JPEG
fig.write_html("kayak_results/rainfall_cities_elimination.html")
print("HTML export completed successfully!")

HTML export completed successfully!

In [80]:
# Removal of the 10 cities that did not meet the rain criteria.

weather_decision_filtered_df = weather_decision_merged_df[weather_decision_merged_df['color'] == 'green (<1mm)']
list_of_cities = weather_decision_filtered_df['city_name'].tolist()

len(list_of_cities) # Check that the list is limited to 25 cities

25

In [85]:
# Obtaining the ranking based on the temperature and UV index criteria

# Make a copy of the sliced DataFrame to avoid the warning
weather_decision_filtered_df = weather_decision_filtered_df.copy()

# Create a new column 'rank_temp' based on the 'avg_temp' column in descending order
weather_decision_filtered_df['rank_temp'] = weather_decision_filtered_df['avg_temp'].rank(ascending=False, method='min').astype(int)

# Create a new column 'rank_uv_index' based on the 'avg_uv_index' column in descending order
weather_decision_filtered_df['rank_uv_index'] = weather_decision_filtered_df['avg_uv_index'].rank(ascending=False, method='min').astype(int)

# Sum of these two columns
weather_decision_filtered_df['overall_rating'] = weather_decision_filtered_df['rank_temp'] + weather_decision_filtered_df['rank_uv_index'].astype(int)

# Final ranking accorind to this overall_rating, in ascending order
weather_decision_filtered_df['final_ranking'] = weather_decision_filtered_df['overall_rating'].rank(ascending=True, method='min').astype(int)

In [ ]:
# Sort the dataframe et see the Top5 cities

weather_decision_filtered_df = weather_decision_filtered_df.sort_values(by='final_ranking', ascending=True)
weather_decision_filtered_df[['city_name','final_ranking']]

                       city_name  final_ranking
30                      Toulouse              1
21               Aix en Provence              2
31                     Montauban              2
18            Bormes les Mimosas              2
20                     Marseille              5
28                   Carcassonne              6
19                        Cassis              6
17              Gorges du Verdon              8
15                      Grenoble              9
34                   La Rochelle             10
3                       Le Havre             11
1                        St Malo             12
14                        Annecy             13
0              Mont Saint Michel             14
12                      Besancon             15
2                         Bayeux             16
5                          Paris             17
11                     Eguisheim             17
4                          Rouen             17
6                         Amiens             20
7                          Lille             21
9   Chateau du Haut Koenigsbourg             21
8                     Strasbourg             21
10                        Colmar             24
13                         Dijon             25

In [189]:
# Same vizualisation on a France map


# Add a column to define the color (Red if > 1mm, Green otherwise)
weather_decision_filtered_df['color'] = weather_decision_filtered_df['final_ranking'].apply(lambda x: 'red (NOT TOP5)' if x > 5 else 'green (TOP5)')

# Create the map with Plotly Express
fig = px.scatter_mapbox(
    weather_decision_filtered_df,
    lat='Latitude',
    lon='Longitude',
    color='color',  # Custom colors
    size=[10] * len(weather_decision_filtered_df),
    hover_name='city_name',
    hover_data={'Latitude': False, 'Longitude': False, 'final_ranking': True},  # Hover info
    color_discrete_map={'red (NOT TOP5)': 'red', 'green (TOP5)': 'green'},  # Custom legend
    title="TOP5 Cities of France",
)

# Customize the display
fig.update_layout(
    height=800,
    width = 1000,
    mapbox_zoom=5,
    mapbox_style="carto-positron",  # Map style
    mapbox_center={"lat": 46.6031, "lon": 1.8883},  # Center on France
    title={
        'text': "TOP5 Cities of France",
        'x': 0.5,
        'xanchor': 'center',
        'font': dict(size=20, color="black")
    }
)

# Display the map
fig.show()

# Store this map in jpeg

fig.write_image("kayak_results/TOP5_cities.jpg", format="jpeg")

print("JPEG storage Done !")

JPEG storage Done !

In [97]:
# Final list of cities
 
TOP5_list_of_cities = weather_decision_filtered_df[weather_decision_filtered_df['final_ranking'] < 6]['city_name'].tolist()

TOP5_list_of_cities # To see the list

['Toulouse', 'Aix en Provence', 'Montauban', 'Bormes les Mimosas', 'Marseille']

<h1 style="font-size: 18px;">
    The TOP5 cities have been well defined, and now we can proceed with scraping data from Booking.com!
</h1>

# 4. Scraping a list of 25 hotel URLs per city

<h1 style="font-size: 18px;">

The goal of this section is to scrape the URLs of various hotel per city, so that we can later scrape all the necessary information from this list of URLs 
</h1>

In [24]:
# Recreate the list of cities to avoid rerunning all previous cells and continue progressing."

import pickle

# Load the variable from the saved file
with open('TOP5_list_of_cities.pkl', 'rb') as f:
    TOP5_list_of_cities = pickle.load(f)

# After a quick check on Booking.com, spaces in the city names are replaced with '-' in the URLs.

TOP5_list_of_cities = [city.replace(" ", "-") for city in TOP5_list_of_cities]
TOP5_list_of_cities

['Toulouse', 'Aix-en-Provence', 'Montauban', 'Bormes-les-Mimosas', 'Marseille']

In [25]:
# Make this variable available for the python spider

import pickle

# Save the variable to a file
with open('TOP5_list_of_cities.pkl', 'wb') as f:
    pickle.dump(TOP5_list_of_cities, f)

In [103]:
# Launch the Spider1_KAYAK to scrap the data

!python Spider1_KAYAK.py

2025-02-08 22:20:32 [scrapy.utils.log] INFO: Scrapy 2.11.1 started (bot: scrapybot)
2025-02-08 22:20:32 [scrapy.utils.log] INFO: Versions: lxml 4.9.3.0, libxml2 2.10.4, cssselect 1.2.0, parsel 1.8.1, w3lib 2.1.2, Twisted 23.10.0, Python 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)], pyOpenSSL 24.0.0 (OpenSSL 3.0.15 3 Sep 2024), cryptography 42.0.2, Platform Windows-10-10.0.19045-SP0
2025-02-08 22:20:32 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-08 22:20:32 [py.warnings] WARNING: c:\Users\valen\anaconda3\Lib\site-packages\scrapy\utils\request.py:254: ScrapyDeprecationWarning: '2.6' is a deprecated value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting.

It is also the default value. In other words, it is normal to get this warning if you have not defined a value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting. This is so for backward compatibility reasons, but it will change in a future version of Scrapy.

See the documentation of the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting for information on how to handle this deprecation.
  return cls(crawler)

2025-02-08 22:20:32 [scrapy.extensions.telnet] INFO: Telnet Password: 35d06201abb43f02
2025-02-08 22:20:33 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-08 22:20:33 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 20, 'USER_AGENT': 'Chrome/97.0'}
2025-02-08 22:20:35 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-02-08 22:20:35 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-02-08 22:20:35 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-02-08 22:20:35 [scrapy.core.engine] INFO: Spider opened
2025-02-08 22:20:35 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-02-08 22:20:35 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2025-02-08 22:20:36 [scrapy.core.engine] INFO: Closing spider (finished)
2025-02-08 22:20:36 [scrapy.extensions.feedexport] INFO: Stored json feed (5 items) in: kayak_results/List_of_URLs_per_TOP5_cities.json
2025-02-08 22:20:36 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 1194,
 'downloader/request_count': 5,
 'downloader/request_method_count/GET': 5,
 'downloader/response_bytes': 1001986,
 'downloader/response_count': 5,
 'downloader/response_status_count/200': 5,
 'elapsed_time_seconds': 1.576504,
 'feedexport/success_count/FileFeedStorage': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2025, 2, 8, 21, 20, 36, 805401, tzinfo=datetime.timezone.utc),
 'httpcompression/response_bytes': 6225766,
 'httpcompression/response_count': 5,
 'item_scraped_count': 5,
 'log_count/INFO': 11,
 'log_count/WARNING': 1,
 'response_received_count': 5,
 'scheduler/dequeued': 5,
 'scheduler/dequeued/memory': 5,
 'scheduler/enqueued': 5,
 'scheduler/enqueued/memory': 5,
 'start_time': datetime.datetime(2025, 2, 8, 21, 20, 35, 228897, tzinfo=datetime.timezone.utc)}
2025-02-08 22:20:36 [scrapy.core.engine] INFO: Spider closed (finished)

In [1]:
# Transformation of the JSON into a Dataframe

import json
import pandas as pd


filepath = 'kayak_results/List_of_URLs_per_TOP5_cities.json'

# Reading of the JSON
with open(filepath, 'r', encoding='utf-8') as file:
    hotels_url = json.load(file)

# Into a dataframe for a better visualization
df_hotels_url = pd.DataFrame(hotels_url)

df_hotels_url

,city,hotel_names,hotel_urls
0,Montauban,"[Brit Hotel Confort Montauban, Appartement Cos...",[https://www.booking.com/hotel/fr/deltour-mont...
1,Marseille,"[The Babel Community Hôtel - Vieux Port, Toyok...",[https://www.booking.com/hotel/fr/grand-t1-vie...
2,Aix-en-Provence,"[thecamp Hôtel & Lodges - Aix en Provence, Séj...",[https://www.booking.com/hotel/fr/thecamp-amp-...
3,Bormes-les-Mimosas,[Cosy 36m avec jolie VUE MER centre-village !...,[https://www.booking.com/hotel/fr/cosy-36m-wit...
4,Toulouse,"[The Social Hub Toulouse, Odalys City Toulouse...",[https://www.booking.com/hotel/fr/the-social-h...

In [8]:
# Cleaning to get a readable list of hotel_urls

df_hotels_url_exploded = df_hotels_url[['city','hotel_names','hotel_urls']].explode(['hotel_names','hotel_urls'], ignore_index=True)
list_of_urls = df_hotels_url_exploded.iloc[:, 1].tolist()

In [26]:
# Make this variable available for the python spider

# Save the variable to a file
with open('list_of_urls.pkl', 'wb') as f:
    pickle.dump(list_of_urls, f)

NameError: name 'list_of_urls' is not defined

<h1 style="font-size: 18px;">
    Now that we have gathered a list of 25 hotel URLs per city, we will be able to scrape various details from these hotels! It can be found in kayak_result/list_of_urls.pkl
</h1>

# 5. Scraping all the hotel details

In [ ]:
# Recreate the list of cities to avoid rerunning all previous cells and continue progressing."

import pickle

# Load the variable from the saved file
with open('list_of_urls.pkl', 'rb') as f:
    list_of_urls = pickle.load(f)

FileNotFoundError: [Errno 2] No such file or directory: 'kayak_results/list_of_urls.pkl'

In [112]:
# Launch the Spider2_KAYAK to scrap the data from the list_of_urls

!python Spider2_KAYAK.py

2025-02-08 22:39:17 [scrapy.utils.log] INFO: Scrapy 2.11.1 started (bot: scrapybot)
2025-02-08 22:39:17 [scrapy.utils.log] INFO: Versions: lxml 4.9.3.0, libxml2 2.10.4, cssselect 1.2.0, parsel 1.8.1, w3lib 2.1.2, Twisted 23.10.0, Python 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)], pyOpenSSL 24.0.0 (OpenSSL 3.0.15 3 Sep 2024), cryptography 42.0.2, Platform Windows-10-10.0.19045-SP0
2025-02-08 22:39:17 [scrapy.addons] INFO: Enabled addons:
[]
2025-02-08 22:39:17 [py.warnings] WARNING: c:\Users\valen\anaconda3\Lib\site-packages\scrapy\utils\request.py:254: ScrapyDeprecationWarning: '2.6' is a deprecated value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting.

It is also the default value. In other words, it is normal to get this warning if you have not defined a value for the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting. This is so for backward compatibility reasons, but it will change in a future version of Scrapy.

See the documentation of the 'REQUEST_FINGERPRINTER_IMPLEMENTATION' setting for information on how to handle this deprecation.
  return cls(crawler)

2025-02-08 22:39:17 [scrapy.extensions.telnet] INFO: Telnet Password: 809cd9aafbcdad1a
2025-02-08 22:39:18 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2025-02-08 22:39:18 [scrapy.crawler] INFO: Overridden settings:
{'LOG_LEVEL': 20, 'USER_AGENT': 'Chrome/97.0'}
2025-02-08 22:39:19 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2025-02-08 22:39:19 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2025-02-08 22:39:19 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2025-02-08 22:39:19 [scrapy.core.engine] INFO: Spider opened
2025-02-08 22:39:19 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2025-02-08 22:39:19 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2025-02-08 22:39:43 [scrapy.core.engine] INFO: Closing spider (finished)
2025-02-08 22:39:43 [scrapy.extensions.feedexport] INFO: Stored json feed (125 items) in: kayak_results/hotels_details.json
2025-02-08 22:39:43 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 156619,
 'downloader/request_count': 125,
 'downloader/request_method_count/GET': 125,
 'downloader/response_bytes': 35077369,
 'downloader/response_count': 125,
 'downloader/response_status_count/200': 125,
 'elapsed_time_seconds': 23.407027,
 'feedexport/success_count/FileFeedStorage': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2025, 2, 8, 21, 39, 43, 344978, tzinfo=datetime.timezone.utc),
 'httpcompression/response_bytes': 164921536,
 'httpcompression/response_count': 125,
 'item_scraped_count': 125,
 'log_count/INFO': 11,
 'log_count/WARNING': 1,
 'response_received_count': 125,
 'scheduler/dequeued': 125,
 'scheduler/dequeued/memory': 125,
 'scheduler/enqueued': 125,
 'scheduler/enqueued/memory': 125,
 'start_time': datetime.datetime(2025, 2, 8, 21, 39, 19, 937951, tzinfo=datetime.timezone.utc)}
2025-02-08 22:39:43 [scrapy.core.engine] INFO: Spider closed (finished)

In [4]:
# Transformation of the JSON into a Dataframe

import json
import pandas as pd


filepath = 'kayak_results/hotels_details.json'

# Reading of the JSON
with open(filepath, 'r', encoding='utf-8') as file:
    hotels_details = json.load(file)

# Into a dataframe for a better visualization
df_hotel_details = pd.DataFrame(hotels_details)

df_hotel_details

,hotel_url,hotel_gps,hotel_desc,hotel_mark
0,https://www.booking.com/hotel/fr/le-point-virg...,"44.0222532,1.3591095","[Situé à Montauban, l’hébergement Le Point Vir...",None
1,https://www.booking.com/hotel/fr/le-beau-malco...,"44.0173306,1.3534844",[Le beau Malcousinat proche place Nationale es...,"9,1"
2,https://www.booking.com/hotel/fr/appartement-c...,"44.0191236,1.3564167",[L'Appartement Cosy en Centre ville est situé ...,"8,2"
3,https://www.booking.com/hotel/fr/dali-montauba...,"44.020995559797,1.349240014017","[Situé à Montauban, le Dali Hôtel Montauban pr...","9,0"
4,https://www.booking.com/hotel/fr/appartement-d...,"44.01682794568838,1.3424564997115507","[Situé à Montauban, l’hébergement L’appartemen...","9,1"
...,...,...,...,...
120,https://www.booking.com/hotel/fr/campanilepurp...,"43.606810036550876,1.3937294483184814",[Cet hôtel Campanile est situé à proximité de ...,"8,5"
121,https://www.booking.com/hotel/fr/residhotel-to...,"43.59539161058483,1.4412049948077765",[L’établissement Residhotel Toulouse Centre se...,"7,9"
122,https://www.booking.com/hotel/fr/cousture.fr.h...,"43.604250797317704,1.4504990726709366",[L’Hôtel Le Cousture vous accueille au cœur de...,"7,6"
123,https://www.booking.com/hotel/fr/le-clos-des-s...,"43.594413616900646,1.44607275724411",[Situé au cœur du centre-ville historique de T...,"9,6"
124,https://www.booking.com/hotel/fr/penitents-by-...,"43.6019883,1.45001","[Situé dans le centre de Toulouse, à 3,8 km du...","8,5"

In [9]:
# Merge of this dataframe with the previous one to get the city_name and data transformation

df_kayak_final = pd.merge(df_hotels_url_exploded, df_hotel_details, left_on='hotel_urls', right_on='hotel_url', how='inner')

# Separation of longitude / latitude
df_kayak_final[['hotel_latitude', 'hotel_longitude']] = df_kayak_final['hotel_gps'].str.split(',', expand=True)

# Keeping of the interesting columns
df_kayak_final = df_kayak_final[['city', 'hotel_names', 'hotel_longitude', 'hotel_latitude', 'hotel_url', 'hotel_desc', 'hotel_mark']]

# Type transformation as float
df_kayak_final['hotel_latitude'] = pd.to_numeric(df_kayak_final['hotel_latitude'], errors='coerce')
df_kayak_final['hotel_longitude'] = pd.to_numeric(df_kayak_final['hotel_longitude'], errors='coerce')

df_kayak_final['hotel_mark'] = df_kayak_final['hotel_mark'].str.replace(',', '.')  # Replace commas
df_kayak_final['hotel_mark'] = pd.to_numeric(df_kayak_final['hotel_mark'], errors='coerce')



df_kayak_final

,city,hotel_names,hotel_longitude,hotel_latitude,hotel_url,hotel_desc,hotel_mark
0,Montauban,Brit Hotel Confort Montauban,1.330394,43.980811,https://www.booking.com/hotel/fr/deltour-monta...,[L’établissement Brit Hotel Confort Montauban ...,8.2
1,Montauban,Appartement Cosy en Centre ville,1.356417,44.019124,https://www.booking.com/hotel/fr/appartement-c...,[L'Appartement Cosy en Centre ville est situé ...,8.2
2,Montauban,Sure Hotel by Best Western Les Portes de Monta...,1.322098,43.936287,https://www.booking.com/hotel/fr/sure-by-best-...,"[Situé à Montauban, à 42 km de l'amphithéâtre ...",8.8
3,Montauban,Hôtel du Commerce,1.354073,44.015426,https://www.booking.com/hotel/fr/hotel-du-comm...,"[Situé dans le centre de Montauban, l'Hôtel du...",8.4
4,Montauban,Dali Hôtel Montauban,1.349240,44.020996,https://www.booking.com/hotel/fr/dali-montauba...,"[Situé à Montauban, le Dali Hôtel Montauban pr...",9.0
...,...,...,...,...,...,...,...
120,Toulouse,Campanile Toulouse Purpan,1.393729,43.606810,https://www.booking.com/hotel/fr/campanilepurp...,[Cet hôtel Campanile est situé à proximité de ...,8.5
121,Toulouse,Pénitents by Yumē,1.450010,43.601988,https://www.booking.com/hotel/fr/penitents-by-...,"[Situé dans le centre de Toulouse, à 3,8 km du...",8.5
122,Toulouse,Residhotel Toulouse Centre,1.441205,43.595392,https://www.booking.com/hotel/fr/residhotel-to...,[L’établissement Residhotel Toulouse Centre se...,7.9
123,Toulouse,Hôtel Le Cousture,1.450499,43.604251,https://www.booking.com/hotel/fr/cousture.fr.h...,[L’Hôtel Le Cousture vous accueille au cœur de...,7.6
124,Toulouse,Le Clos des Salins,1.446073,43.594414,https://www.booking.com/hotel/fr/le-clos-des-s...,[Situé au cœur du centre-ville historique de T...,9.6

In [12]:
# Storage of this important table in a CSV

df_kayak_final.to_csv(os.path.join('kayak_results', f"kayak_final_details.csv"), index=False)

<h1 style="font-size: 18px;">
    The dataframe df_kayak_final contains all the expected information and has been stored in a CSV file named kayak_results/kayak_final_details.
</h1>

<h1 style="font-size: 18px;">
    Let's assume we want to view the top 20 highest-ranked hotels from the entire scraped list
</h1>

In [13]:
# Filtering the non-marked hotel (must not be considered in our case)

df_kayak_final = df_kayak_final[df_kayak_final['hotel_mark'].notnull()]

In [14]:
# Filtering the non-marked hotel (must not be considered in our case)

df_kayak_TOP20_hotels = df_kayak_final.sort_values(by='hotel_mark', ascending=False).head(20)
df_kayak_TOP20_hotels

,city,hotel_names,hotel_longitude,hotel_latitude,hotel_url,hotel_desc,hotel_mark
77,Bormes-les-Mimosas,SELECT'soHOME - Superbe appartement pour 4 per...,6.359008,43.124624,https://www.booking.com/hotel/fr/select-sohome...,[Situé à 700 mètres de la plage de la Pointe d...,10.0
13,Montauban,Villa de cammas,1.317364,44.013202,https://www.booking.com/hotel/fr/villa-de-camm...,"[Située à Montauban, en Midi-Pyrénées, la Vill...",9.8
14,Montauban,L'authentique,1.355709,44.017520,https://www.booking.com/hotel/fr/authentique-m...,[L'authentique est situé à Montauban. Une conn...,9.7
41,Marseille,Résidence Kley Marseille République,5.369920,43.301093,https://www.booking.com/hotel/fr/residence-kle...,[La Résidence Kley Marseille République est si...,9.7
124,Toulouse,Le Clos des Salins,1.446073,43.594414,https://www.booking.com/hotel/fr/le-clos-des-s...,[Situé au cœur du centre-ville historique de T...,9.6
88,Bormes-les-Mimosas,The Little House,6.342202,43.150361,https://www.booking.com/hotel/fr/the-little-ho...,"[Situé à Bormes-les-Mimosas, à 29 km du châtea...",9.6
81,Bormes-les-Mimosas,Cosy studio - Place du Figuier,6.342968,43.151455,https://www.booking.com/hotel/fr/studio-figuie...,"[Situé à Bormes-les-Mimosas, à 29 km du châtea...",9.6
11,Montauban,La Halte Occitane - Classé 3 étoiles - Pour 6 ...,1.315446,44.015068,https://www.booking.com/hotel/fr/beau-t4-tout-...,"[Situé à Montauban, l’hébergement La Halte Occ...",9.6
42,Marseille,Élégant appartement - centre Prado Vélodrome,5.387800,43.269802,https://www.booking.com/hotel/fr/elegant-appar...,"[Situé à Marseille, à 1,7 km de la plage de l'...",9.6
90,Bormes-les-Mimosas,SELECT' - T2 avec vue - Piscine et parking pri...,6.352916,43.142718,https://www.booking.com/hotel/fr/select-t2-ave...,[L’hébergement SELECT' - T2 avec vue - Piscine...,9.5
12,Montauban,"Chez Juliette, proche Place Nationale avec par...",1.354858,44.018036,https://www.booking.com/hotel/fr/chez-juliette...,"[Situé à Montauban, en Midi-Pyrénées, l'établi...",9.5
34,Marseille,Marseille City Chambres&Appartements,5.372294,43.301957,https://www.booking.com/hotel/fr/marseillecity...,[Le Marseille City Chambres&Appartements propo...,9.4
93,Bormes-les-Mimosas,Boulevard du Soleil,6.341970,43.149233,https://www.booking.com/hotel/fr/boulevard-du-...,"[Situé à Bormes-les-Mimosas, à seulement 29 km...",9.4
86,Bormes-les-Mimosas,Les Terrasses de Lô,6.353536,43.143885,https://www.booking.com/hotel/fr/les-terrasses...,[Doté d'une baignoire en plein air et offrant ...,9.4
76,Bormes-les-Mimosas,"Bord de mer, charmant studio entièrement équipé",6.358852,43.126023,https://www.booking.com/hotel/fr/bord-de-mer-c...,"[L’hébergement Bord de mer, charmant studio en...",9.4
67,Aix-en-Provence,Villa ELISABETH,5.447192,43.534034,https://www.booking.com/hotel/fr/villa-elisabe...,[L’hébergement Villa ELISABETH se trouve à Aix...,9.4
63,Aix-en-Provence,Charmant appartement 2 pièces en plein centre ...,5.450302,43.529795,https://www.booking.com/hotel/fr/charmant-appa...,"[Situé à Aix-en-Provence, à 32 km de la statio...",9.4
8,Montauban,Studio plein Sud au calme,1.326678,44.007775,https://www.booking.com/hotel/fr/studios-plein...,"[Situé à Montauban, l’établissement Studio ple...",9.3
59,Aix-en-Provence,Chambre style balinais,5.452377,43.528428,https://www.booking.com/hotel/fr/chambre-style...,"[Doté d’une connexion Wi-Fi gratuite, l’héberg...",9.3
56,Aix-en-Provence,Bel Appartement dans le centre d'Aix-en-Provence,5.449251,43.531008,https://www.booking.com/hotel/fr/bel-apparteme...,"[Situé dans le centre d'Aix-en-Provence, à 31 ...",9.3

In [17]:
# Visualize the TOP20Hotels in a French map

# Adjust the size of the markers based on 'hotel_mark'
size_max = 30 
min_size = 5 
df_kayak_TOP20_hotels['normalized_size'] = (df_kayak_TOP20_hotels['hotel_mark'] - df_kayak_TOP20_hotels['hotel_mark'].min()) / (df_kayak_TOP20_hotels['hotel_mark'].max() - df_kayak_TOP20_hotels['hotel_mark'].min()) * (size_max - min_size) + min_size

# Create the map with Plotly Express
fig = px.scatter_mapbox(
    df_kayak_TOP20_hotels,
    lat='hotel_latitude',
    lon='hotel_longitude',
    size='normalized_size',  # Size based on the normalized hotel_mark
    hover_name='city',
    hover_data={'hotel_latitude': False, 'hotel_longitude': False, 'hotel_mark': True},  # Hover info
    title="TOP20 Hotels of TOP5 cities",
)

# Customize the display
fig.update_layout(
    height=800,
    width=1000,
    mapbox_zoom=6.5,
    mapbox_style="carto-positron",  # Map style
    mapbox_center={"lat": 43.62, "lon": 3.86},  # relevant place defined by testing
    title={
        'text': "TOP20 Hotels of TOP5 cities",
        'x': 0.5,
        'xanchor': 'center',
        'font': dict(size=20, color="black")
    }
)

# Display the map
fig.show()

# Store this map in jpeg

fig.write_image("kayak_results/TOP20_Hotels_of_TOP5_cities.jpg", format="jpeg")

print("JPEG storage Done !")

JPEG storage Done !

In [188]:
# As the map is wide, let's zoom on one city to ensure this is correct

# Adjust the size of the markers based on 'hotel_mark'
size_max = 30 
min_size = 5 
df_kayak_TOP20_hotels['normalized_size'] = (df_kayak_TOP20_hotels['hotel_mark'] - df_kayak_TOP20_hotels['hotel_mark'].min()) / (df_kayak_TOP20_hotels['hotel_mark'].max() - df_kayak_TOP20_hotels['hotel_mark'].min()) * (size_max - min_size) + min_size

# Create the map with Plotly Express
fig = px.scatter_mapbox(
    df_kayak_TOP20_hotels,
    lat='hotel_latitude',
    lon='hotel_longitude',
    size='normalized_size',  # Size based on the normalized hotel_mark
    hover_name='city',
    hover_data={'hotel_latitude': False, 'hotel_longitude': False, 'hotel_mark': True},  # Hover info
    title="TOP20 Hotels of Marseille",
)

# Customize the display
fig.update_layout(
    height=800,
    width=1000,
    mapbox_zoom=12,
    mapbox_style="carto-positron",  # Map style
    mapbox_center={"lat": 43.30, "lon": 5.4},  # relevant place defined by testing
    title={
        'text': "TOP20 Hotels of Marseille",
        'x': 0.5,
        'xanchor': 'center',
        'font': dict(size=20, color="black")
    }
)

# Display the map
fig.show()

# Store this map in jpeg

fig.write_image("kayak_results/Final_example_on_Marseille.jpg", format="jpeg")

print("JPEG storage Done !")

JPEG storage Done !

<h1 style="font-size: 18px;">
    We have successfully generated the map displaying the 20 selected hotels, with a zoom-in on the city of Marseille to ensure optimal visualization
</h1>

# 6. Placing the dataset "kayak_final_details.csv" into AWS S3

<h1 style="font-size: 18px;">
    A specific S3 bucket called 'kayak-project-loicvalentini' has been created.
</h1>

<a href="https://ibb.co/nNrbKggB"><img src="https://i.ibb.co/PvxNVmmM/S3-Bucket.jpg" alt="S3-Bucket" border="0" /></a>

<h1 style="font-size: 18px;">
    The dataset 'kayak_final_details.csv' has been uploaded to this new bucket via drag and drop.
</h1>

<a href="https://ibb.co/ch21Gv28"><img src="https://i.ibb.co/23cyD6cM/S3-File.jpg" alt="S3-File" border="0" /></a>

<h1 style="font-size: 18px;">
    But also with python code.
</h1>

In [1]:
# Necessary libraries to import

import boto3
from dotenv import load_dotenv
import os
import pandas as pd
load_dotenv()

True

In [2]:
# AWS Session to open

session = boto3.Session(aws_access_key_id=os.getenv("AWS_KEY"), 
                        aws_secret_access_key=os.getenv("AWS_SECRET_KEY"))

In [8]:
# Creation of the necessary S3 variables

s3 = session.resource('s3')
bucket_name = "kayak-project-loicvalentini"
bucket = s3.Bucket(bucket_name)

In [ ]:
# Reimport of the kayak_final_results data and generation of a CSV variable

df_kayak_final_results = pd.read_csv('kayak_results/kayak_final_details.csv')
df_kayak_final_results.csv = df_kayak_final_results.to_csv()

In [ ]:
# CSV file to put into the S3 bucket

put_object = bucket.put_object(Key="df_kayak_final_results.csv", Body=df_kayak_final_results.csv)

<a href="https://ibb.co/DH3mNv00"><img src="https://i.ibb.co/4nBCcXhh/S3-Bucket-code-version.jpg" alt="S3-Bucket-code-version" border="0" /></a>

<h1 style="font-size: 18px;">
    Next, let's make it available in an SQL database.
</h1>

# 7.  Availability of the dataset on AWS RDS

<h1 style="font-size: 18px;">
    A specific RDS database bucket called 'database-kayak-details-loicvalentini' has been created.
</h1>

<a href="https://ibb.co/qLYvG54L"><img src="https://i.ibb.co/p6jSDys6/RDS-Database.jpg" alt="RDS-Database" border="0" /></a>

<h1 style="font-size: 18px;">
    Now, let's set up a functional database.
</h1>

In [1]:
# Necessary imports

from sqlalchemy import create_engine, text
from dotenv import load_dotenv
import boto3
import os 
import pandas as pd
from io import StringIO

load_dotenv()

True

In [ ]:
# Retrieving the csv file from S3

# Creation of s3 client

s3_client = boto3.client(
    's3',
    aws_access_key_id=os.getenv("AWS_KEY"), 
    aws_secret_access_key=os.getenv("AWS_SECRET_KEY")
)

# Uploading the file from s3

bucket_name = 'kayak-project-loicvalentini'
file_key = 'kayak_final_details.csv'

response = s3_client.get_object(Bucket=bucket_name, Key=file_key)
file_content = response['Body'].read().decode('utf-8')

In [ ]:
# Engine creation

engine = create_engine(f"postgresql+psycopg2://{os.getenv('POSTGRE_USERNAME')}:{os.getenv('POSTGRE_PASSWORD')}@{os.getenv('POSTGRE_HOSTNAME')}", echo=True)

In [ ]:
# Replacing this .csv by a pandas Dataframe

df_kayak = pd.read_csv(StringIO(file_content))

In [ ]:
# Insertion of this data into RDS

df_kayak.to_sql('database_kayak_details', con=engine, if_exists='replace', index=False)

2025-02-10 20:31:53,713 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2025-02-10 20:31:53,714 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-02-10 20:31:53,731 INFO sqlalchemy.engine.Engine select current_schema()
2025-02-10 20:31:53,733 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-02-10 20:31:53,750 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2025-02-10 20:31:53,751 INFO sqlalchemy.engine.Engine [raw sql] {}
2025-02-10 20:31:53,778 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-02-10 20:31:53,789 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-02-10 20:31:53,791 INFO sqlalchemy.engine.Engine [generated in 0.00216s] {'table_name': 'database_kayak_details', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-02-10 20:31:53,815 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-02-10 20:31:53,816 INFO sqlalchemy.engine.Engine [cached since 0.0275s ago] {'table_name': 'database_kayak_details', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2025-02-10 20:31:53,831 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s]) AND pg_catalog.pg_class.relpersistence != %(relpersistence_1)s AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-02-10 20:31:53,832 INFO sqlalchemy.engine.Engine [generated in 0.00164s] {'param_1': 'r', 'param_2': 'p', 'relpersistence_1': 't', 'nspname_1': 'pg_catalog'}
2025-02-10 20:31:53,848 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s]) AND pg_catalog.pg_class.relpersistence != %(relpersistence_1)s AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-02-10 20:31:53,850 INFO sqlalchemy.engine.Engine [generated in 0.00169s] {'param_1': 'v', 'relpersistence_1': 't', 'nspname_1': 'pg_catalog'}
2025-02-10 20:31:53,864 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s]) AND pg_catalog.pg_class.relpersistence != %(relpersistence_1)s AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2025-02-10 20:31:53,866 INFO sqlalchemy.engine.Engine [cached since 0.01767s ago] {'param_1': 'm', 'relpersistence_1': 't', 'nspname_1': 'pg_catalog'}
2025-02-10 20:31:53,898 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_attribute.attname AS name, pg_catalog.format_type(pg_catalog.pg_attribute.atttypid, pg_catalog.pg_attribute.atttypmod) AS format_type, (SELECT pg_catalog.pg_get_expr(pg_catalog.pg_attrdef.adbin, pg_catalog.pg_attrdef.adrelid) AS pg_get_expr_1
FROM pg_catalog.pg_attrdef
WHERE pg_catalog.pg_attrdef.adrelid = pg_catalog.pg_attribute.attrelid AND pg_catalog.pg_attrdef.adnum = pg_catalog.pg_attribute.attnum AND pg_catalog.pg_attribute.atthasdef) AS "default", pg_catalog.pg_attribute.attnotnull AS not_null, pg_catalog.pg_class.relname AS table_name, pg_catalog.pg_description.description AS comment, pg_catalog.pg_attribute.attgenerated AS generated, (SELECT json_build_object(%(json_build_object_2)s, pg_catalog.pg_attribute.attidentity = %(attidentity_1)s, %(json_build_object_3)s, pg_catalog.pg_sequence.seqstart, %(json_build_object_4)s, pg_catalog.pg_sequence.seqincrement, %(json_build_object_5)s, pg_catalog.pg_sequence.seqmin, %(json_build_object_6)s, pg_catalog.pg_sequence.seqmax, %(json_build_object_7)s, pg_catalog.pg_sequence.seqcache, %(json_build_object_8)s, pg_catalog.pg_sequence.seqcycle) AS json_build_object_1
FROM pg_catalog.pg_sequence
WHERE pg_catalog.pg_attribute.attidentity != %(attidentity_2)s AND pg_catalog.pg_sequence.seqrelid = CAST(CAST(pg_catalog.pg_get_serial_sequence(CAST(CAST(pg_catalog.pg_attribute.attrelid AS REGCLASS) AS TEXT), pg_catalog.pg_attribute.attname) AS REGCLASS) AS OID)) AS identity_options
FROM pg_catalog.pg_class LEFT OUTER JOIN pg_catalog.pg_attribute ON pg_catalog.pg_class.oid = pg_catalog.pg_attribute.attrelid AND pg_catalog.pg_attribute.attnum > %(attnum_1)s AND NOT pg_catalog.pg_attribute.attisdropped LEFT OUTER JOIN pg_catalog.pg_description ON pg_catalog.pg_description.objoid = pg_catalog.pg_attribute.attrelid AND pg_catalog.pg_description.objsubid = pg_catalog.pg_attribute.attnum JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s AND pg_catalog.pg_class.relname IN (%(filter_names_1)s) ORDER BY pg_catalog.pg_class.relname, pg_catalog.pg_attribute.attnum
2025-02-10 20:31:53,900 INFO sqlalchemy.engine.Engine [generated in 0.00227s] {'json_build_object_2': 'always', 'attidentity_1': 'a', 'json_build_object_3': 'start', 'json_build_object_4': 'increment', 'json_build_object_5': 'minvalue', 'json_build_object_6': 'maxvalue', 'json_build_object_7': 'cache', 'json_build_object_8': 'cycle', 'attidentity_2': '', 'attnum_1': 0, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog', 'filter_names_1': 'database_kayak_details'}
2025-02-10 20:31:53,938 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_type.typname AS name, pg_catalog.format_type(pg_catalog.pg_type.typbasetype, pg_catalog.pg_type.typtypmod) AS attype, NOT pg_catalog.pg_type.typnotnull AS nullable, pg_catalog.pg_type.typdefault AS "default", pg_catalog.pg_type_is_visible(pg_catalog.pg_type.oid) AS visible, pg_catalog.pg_namespace.nspname AS schema, domain_constraints.condefs, domain_constraints.connames
FROM pg_catalog.pg_type JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_type.typnamespace LEFT OUTER JOIN (SELECT pg_catalog.pg_constraint.contypid AS contypid, array_agg(pg_catalog.pg_get_constraintdef(pg_catalog.pg_constraint.oid, %(pg_get_constraintdef_1)s)) AS condefs, array_agg(pg_catalog.pg_constraint.conname) AS connames
FROM pg_catalog.pg_constraint
WHERE pg_catalog.pg_constraint.contypid != %(contypid_1)s GROUP BY pg_catalog.pg_constraint.contypid) AS domain_constraints ON pg_catalog.pg_type.oid = domain_constraints.contypid
WHERE pg_catalog.pg_type.typtype = %(typtype_1)s ORDER BY pg_catalog.pg_namespace.nspname, pg_catalog.pg_type.typname
2025-02-10 20:31:53,941 INFO sqlalchemy.engine.Engine [generated in 0.00349s] {'pg_get_constraintdef_1': True, 'contypid_1': 0, 'typtype_1': 'd'}
2025-02-10 20:31:53,972 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_type.typname AS name, pg_catalog.pg_type_is_visible(pg_catalog.pg_type.oid) AS visible, pg_catalog.pg_namespace.nspname AS schema, lbl_agg.labels AS labels
FROM pg_catalog.pg_type JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_type.typnamespace LEFT OUTER JOIN (SELECT pg_catalog.pg_enum.enumtypid AS enumtypid, array_agg(pg_catalog.pg_enum.enumlabel ORDER BY pg_catalog.pg_enum.enumsortorder) AS labels
FROM pg_catalog.pg_enum GROUP BY pg_catalog.pg_enum.enumtypid) AS lbl_agg ON pg_catalog.pg_type.oid = lbl_agg.enumtypid
WHERE pg_catalog.pg_type.typtype = %(typtype_1)s ORDER BY pg_catalog.pg_namespace.nspname, pg_catalog.pg_type.typname
2025-02-10 20:31:53,975 INFO sqlalchemy.engine.Engine [generated in 0.00319s] {'typtype_1': 'e'}
2025-02-10 20:31:53,996 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.oid, pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s AND pg_catalog.pg_class.relname IN (%(filter_names_1)s)
2025-02-10 20:31:53,999 INFO sqlalchemy.engine.Engine [generated in 0.00290s] {'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog', 'filter_names_1': 'database_kayak_details'}
2025-02-10 20:31:54,018 INFO sqlalchemy.engine.Engine SELECT attr.conrelid, array_agg(attr.attname ORDER BY attr.ord) AS cols, attr.conname, min(attr.description) AS description
FROM (SELECT con.conrelid AS conrelid, con.conname AS conname, con.description AS description, con.ord AS ord, pg_catalog.pg_attribute.attname AS attname
FROM pg_catalog.pg_attribute JOIN (SELECT pg_catalog.pg_constraint.conrelid AS conrelid, pg_catalog.pg_constraint.conname AS conname, unnest(pg_catalog.pg_constraint.conkey) AS attnum, generate_subscripts(pg_catalog.pg_constraint.conkey, %(generate_subscripts_1)s) AS ord, pg_catalog.pg_description.description AS description
FROM pg_catalog.pg_constraint LEFT OUTER JOIN pg_catalog.pg_description ON pg_catalog.pg_description.objoid = pg_catalog.pg_constraint.oid
WHERE pg_catalog.pg_constraint.contype = %(contype)s AND pg_catalog.pg_constraint.conrelid IN (%(oids_1)s)) AS con ON pg_catalog.pg_attribute.attnum = con.attnum AND pg_catalog.pg_attribute.attrelid = con.conrelid) AS attr GROUP BY attr.conrelid, attr.conname ORDER BY attr.conrelid, attr.conname
2025-02-10 20:31:54,019 INFO sqlalchemy.engine.Engine [generated in 0.00207s] {'generate_subscripts_1': 1, 'contype': 'p', 'oids_1': 16467}
2025-02-10 20:31:54,050 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname, pg_catalog.pg_constraint.conname, CASE WHEN (pg_catalog.pg_constraint.oid IS NOT NULL) THEN pg_catalog.pg_get_constraintdef(pg_catalog.pg_constraint.oid, %(pg_get_constraintdef_1)s) END AS anon_1, nsp_ref.nspname, pg_catalog.pg_description.description
FROM pg_catalog.pg_class LEFT OUTER JOIN pg_catalog.pg_constraint ON pg_catalog.pg_class.oid = pg_catalog.pg_constraint.conrelid AND pg_catalog.pg_constraint.contype = %(contype_1)s LEFT OUTER JOIN pg_catalog.pg_class AS cls_ref ON cls_ref.oid = pg_catalog.pg_constraint.confrelid LEFT OUTER JOIN pg_catalog.pg_namespace AS nsp_ref ON cls_ref.relnamespace = nsp_ref.oid LEFT OUTER JOIN pg_catalog.pg_description ON pg_catalog.pg_description.objoid = pg_catalog.pg_constraint.oid JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s AND pg_catalog.pg_class.relname IN (%(filter_names_1)s) ORDER BY pg_catalog.pg_class.relname, pg_catalog.pg_constraint.conname
2025-02-10 20:31:54,052 INFO sqlalchemy.engine.Engine [generated in 0.00204s] {'pg_get_constraintdef_1': True, 'contype_1': 'f', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog', 'filter_names_1': 'database_kayak_details'}
2025-02-10 20:31:54,090 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_index.indrelid, cls_idx.relname AS relname_index, pg_catalog.pg_index.indisunique, pg_catalog.pg_constraint.conrelid IS NOT NULL AS has_constraint, pg_catalog.pg_index.indoption, cls_idx.reloptions, pg_catalog.pg_am.amname, CASE WHEN (pg_catalog.pg_index.indpred IS NOT NULL) THEN pg_catalog.pg_get_expr(pg_catalog.pg_index.indpred, pg_catalog.pg_index.indrelid) ELSE NULL END AS filter_definition, pg_catalog.pg_index.indnkeyatts, idx_cols.elements, idx_cols.elements_is_expr
FROM pg_catalog.pg_index JOIN pg_catalog.pg_class AS cls_idx ON pg_catalog.pg_index.indexrelid = cls_idx.oid JOIN pg_catalog.pg_am ON cls_idx.relam = pg_catalog.pg_am.oid LEFT OUTER JOIN (SELECT idx_attr.indexrelid AS indexrelid, min(idx_attr.indrelid) AS min_1, array_agg(idx_attr.element ORDER BY idx_attr.ord) AS elements, array_agg(idx_attr.is_expr ORDER BY idx_attr.ord) AS elements_is_expr
FROM (SELECT idx.indexrelid AS indexrelid, idx.indrelid AS indrelid, idx.ord AS ord, CASE WHEN (idx.attnum = %(attnum_1)s) THEN pg_catalog.pg_get_indexdef(idx.indexrelid, idx.ord + %(ord_1)s, %(pg_get_indexdef_1)s) ELSE pg_catalog.pg_attribute.attname END AS element, idx.attnum = %(attnum_2)s AS is_expr
FROM (SELECT pg_catalog.pg_index.indexrelid AS indexrelid, pg_catalog.pg_index.indrelid AS indrelid, unnest(pg_catalog.pg_index.indkey) AS attnum, generate_subscripts(pg_catalog.pg_index.indkey, %(generate_subscripts_1)s) AS ord
FROM pg_catalog.pg_index
WHERE NOT pg_catalog.pg_index.indisprimary AND pg_catalog.pg_index.indrelid IN (%(oids_1)s)) AS idx LEFT OUTER JOIN pg_catalog.pg_attribute ON pg_catalog.pg_attribute.attnum = idx.attnum AND pg_catalog.pg_attribute.attrelid = idx.indrelid
WHERE idx.indrelid IN (%(oids_1)s)) AS idx_attr GROUP BY idx_attr.indexrelid) AS idx_cols ON pg_catalog.pg_index.indexrelid = idx_cols.indexrelid LEFT OUTER JOIN pg_catalog.pg_constraint ON pg_catalog.pg_index.indrelid = pg_catalog.pg_constraint.conrelid AND pg_catalog.pg_index.indexrelid = pg_catalog.pg_constraint.conindid AND pg_catalog.pg_constraint.contype = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s])
WHERE pg_catalog.pg_index.indrelid IN (%(oids_1)s) AND NOT pg_catalog.pg_index.indisprimary ORDER BY pg_catalog.pg_index.indrelid, cls_idx.relname
2025-02-10 20:31:54,092 INFO sqlalchemy.engine.Engine [generated in 0.00308s] {'attnum_1': 0, 'ord_1': 1, 'pg_get_indexdef_1': True, 'attnum_2': 0, 'generate_subscripts_1': 1, 'param_1': 'p', 'param_2': 'u', 'param_3': 'x', 'oids_1': 16467}
2025-02-10 20:31:54,108 INFO sqlalchemy.engine.Engine SELECT attr.conrelid, array_agg(attr.attname ORDER BY attr.ord) AS cols, attr.conname, min(attr.description) AS description
FROM (SELECT con.conrelid AS conrelid, con.conname AS conname, con.description AS description, con.ord AS ord, pg_catalog.pg_attribute.attname AS attname
FROM pg_catalog.pg_attribute JOIN (SELECT pg_catalog.pg_constraint.conrelid AS conrelid, pg_catalog.pg_constraint.conname AS conname, unnest(pg_catalog.pg_constraint.conkey) AS attnum, generate_subscripts(pg_catalog.pg_constraint.conkey, %(generate_subscripts_1)s) AS ord, pg_catalog.pg_description.description AS description
FROM pg_catalog.pg_constraint LEFT OUTER JOIN pg_catalog.pg_description ON pg_catalog.pg_description.objoid = pg_catalog.pg_constraint.oid
WHERE pg_catalog.pg_constraint.contype = %(contype)s AND pg_catalog.pg_constraint.conrelid IN (%(oids_1)s)) AS con ON pg_catalog.pg_attribute.attnum = con.attnum AND pg_catalog.pg_attribute.attrelid = con.conrelid) AS attr GROUP BY attr.conrelid, attr.conname ORDER BY attr.conrelid, attr.conname
2025-02-10 20:31:54,110 INFO sqlalchemy.engine.Engine [cached since 0.09286s ago] {'generate_subscripts_1': 1, 'contype': 'u', 'oids_1': 16467}
2025-02-10 20:31:54,124 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname, pg_catalog.pg_description.description
FROM pg_catalog.pg_class LEFT OUTER JOIN pg_catalog.pg_description ON pg_catalog.pg_class.oid = pg_catalog.pg_description.objoid AND pg_catalog.pg_description.objsubid = %(objsubid_1)s JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s AND pg_catalog.pg_class.relname IN (%(filter_names_1)s)
2025-02-10 20:31:54,126 INFO sqlalchemy.engine.Engine [generated in 0.00210s] {'objsubid_1': 0, 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog', 'filter_names_1': 'database_kayak_details'}
2025-02-10 20:31:54,145 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname, pg_catalog.pg_constraint.conname, CASE WHEN (pg_catalog.pg_constraint.oid IS NOT NULL) THEN pg_catalog.pg_get_constraintdef(pg_catalog.pg_constraint.oid, %(pg_get_constraintdef_1)s) END AS anon_1, pg_catalog.pg_description.description
FROM pg_catalog.pg_class LEFT OUTER JOIN pg_catalog.pg_constraint ON pg_catalog.pg_class.oid = pg_catalog.pg_constraint.conrelid AND pg_catalog.pg_constraint.contype = %(contype_1)s LEFT OUTER JOIN pg_catalog.pg_description ON pg_catalog.pg_description.objoid = pg_catalog.pg_constraint.oid JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s AND pg_catalog.pg_class.relname IN (%(filter_names_1)s) ORDER BY pg_catalog.pg_class.relname, pg_catalog.pg_constraint.conname
2025-02-10 20:31:54,147 INFO sqlalchemy.engine.Engine [generated in 0.00252s] {'pg_get_constraintdef_1': True, 'contype_1': 'c', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog', 'filter_names_1': 'database_kayak_details'}
2025-02-10 20:31:54,161 INFO sqlalchemy.engine.Engine
DROP TABLE database_kayak_details
2025-02-10 20:31:54,162 INFO sqlalchemy.engine.Engine [no key 0.00172s] {}
2025-02-10 20:31:54,180 INFO sqlalchemy.engine.Engine
CREATE TABLE database_kayak_details (
	city TEXT,
	hotel_longitude FLOAT(53),
	hotel_latitude FLOAT(53),
	hotel_url TEXT,
	hotel_desc TEXT,
	hotel_mark FLOAT(53)
)


2025-02-10 20:31:54,181 INFO sqlalchemy.engine.Engine [no key 0.00149s] {}
2025-02-10 20:31:54,200 INFO sqlalchemy.engine.Engine INSERT INTO database_kayak_details (city, hotel_longitude, hotel_latitude, hotel_url, hotel_desc, hotel_mark) VALUES (%(city__0)s, %(hotel_longitude__0)s, %(hotel_latitude__0)s, %(hotel_url__0)s, %(hotel_desc__0)s, %(hotel_mark__0)s), (%(city__1)s, % ... 15355 characters truncated ... itude__124)s, %(hotel_latitude__124)s, %(hotel_url__124)s, %(hotel_desc__124)s, %(hotel_mark__124)s)

125

<h1 style="font-size: 18px;">
    This table can also be viewed in PgAdmin, which is connected to RDS.
</h1>

<a href="https://ibb.co/zVPfXwsk"><img src="https://i.ibb.co/3mShpH1J/Pg-Admin-Table.jpg" alt="Pg-Admin-Table" border="0" /></a>

<h1 style="font-size: 18px;">
    It is now fully ready for use to perform further analysis !
</h1>